[~] Testing jobs

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -21,7 +21,16 @@ jobs:
         with:
           fetch-depth: 0
       - name: check_repo_cleanliness
-        run: for i in "$(find . -type f -name "*.o" -o -name "#*#" -o -name "*~" -o -name "*.a" -o -name "*.so" -o -iname "*pain_au_chocolat*" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -type d -name "tmp")"; do echo "::error title=Unwanted file detected,file=${i}::${i}"; if [ i > 0 ]; then exit 84; fi; done
+        run: |
+            count = 0;
+            for i in "$(find . -type f -name "*.o" -o -name "#*#" -o -name "*~" -o -name "*.a" -o -name "*.so" -o -iname "*pain_au_chocolat*" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -type d -name "tmp")";
+            do 
+              echo "::error title=Unwanted file detected,file=${i}::${i}";
+              count = $((count + 1));
+            if [ count > 0 ]; 
+              then exit 84;
+            fi;
+            done
 
   check_program_compilation:
     runs-on: ubuntu-latest
