[~] Testing jobs

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -53,8 +53,9 @@ jobs:
           for binaries in $exec_list;
           do
             if test ! -x $binaries;
-              then echo "::error title=Build Error";
-              exit 1;
+              then
+                echo "::error title=Build Error";
+                exit 1;
             fi;
           done;
 
